export const DemoResultStyles = {
  Result: {
    container:{
        Laptop: {
           topPadding: '60px', 
           bottomPadding: '64px',
            borderBottomRightRadius: '18px',
            borderBottomLeftRadius: '18px',
            borderTopRightRadius: '18px',
            borderTopLeftRadius: '18px',
            borderBottomWidth: '1px',
            borderLeftWidth: '1px',
            borderRightWidth: '1px',
            borderTopWidth: '1px',
            borderTopColor: 'rgba(65, 57, 96, 0.5)',
            borderLeftColor: 'rgba(65, 57, 96, 0.5)',
            borderRightColor: 'rgba(65, 57, 96, 0.5)',
            borderBottomColor: 'rgba(65, 57, 96, 0.5)',
        //    border:'1px',
        //    borderColor:'rgba(65, 57, 96, 0.5)',
           marginLeft:'33px',
           marginRight:'33px',
           marginBottom:'120px',
           height:'348px',
           width:'1374px',
        //    radius:'18px',
        },
        Mobile: {
            topPadding: '88px', 
           bottomPadding: '92px',
           rightPadding: '28px',
           leftPadding: '30px',
           borderBottomRightRadius: '18px',
            borderBottomLeftRadius: '18px',
            borderTopRightRadius: '18px',
            borderTopLeftRadius: '18px',
        borderBottomWidth: '1px',
        borderLeftWidth: '1px',
        borderRightWidth: '1px',
        borderTopWidth: '1px',
        borderTopColor: 'rgba(65, 57, 96, 0.5)',
        borderLeftColor: 'rgba(65, 57, 96, 0.5)',
        borderRightColor: 'rgba(65, 57, 96, 0.5)',
        borderBottomColor: 'rgba(65, 57, 96, 0.5)',
        //    border:'1px',
        //    borderColor:'rgba(97, 67, 216, 0.5)',
           marginLeft:'16px',
           marginRight:'15px',
           marginBottom:'120px',
           height:'438px',
           width:'343px',
        //    radius:'18px',
        }
    },
    title: {
      Laptop: {
        fontSize: '42px',
        fontWeight: '500',
        fontFamily: 'Sharp Grotesk Medium',
        //LetterSpacing: '0.5px',
        color: 'rgb(255, 255, 255)',
        lineHeight: '48px',
        textAlignment: 'center',
        marginBottom: '12px'
      },
  
      Mobile: {
        fontSize: '26px',
        fontWeight: '500',
        fontFamily: 'Sharp Grotesk Medium',
        //LetterSpacing: '0.5px',
        color: 'rgb(255, 255, 255)',
        lineHeight: '28px',
        textAlignment: 'center',
        marginBottom: '12px'
      },
    },
    subtitle: {
      Laptop: {
        fontSize: '18px',
        fontWeight: '400',
        fontFamily: 'Graphik LC TT',
        //LetterSpacing: '0.5px',
        color: 'rgba(255, 255, 255, 1)',
        lineHeight: '28px',
        marginBottom: '32px'
      },
      Mobile: {
        fontSize: '16px',
        fontWeight: '400',
        fontFamily: 'Graphik LC TT',
        //LetterSpacing: '0.5px',
        color: 'rgba(255, 255, 255, 1)',
        lineHeight: '28px',
        marginBottom: '32px'
      },
    },
      talkToAnExoertButton: {

       Laptop: {
        height: '56px',
        width: '284px',
        fontSize: '18px',
        fontFamily: 'Graphik LC TT',
        paddingLeft:' 66px',
        paddingRight:' 66px',
        paddingBottom: '14px',
        paddingTop: '14px',
        borderBottomRightRadius: '8px',
        borderBottomLeftRadius: '8px',
        borderTopRightRadius: '8px',
        borderTopLeftRadius: '8px',
        fontWeight: '500',
        //letterSpacing: '0.5px',
        textAlign: 'center',
        color: 'rgba(255, 255, 255, 1)',
        lineHeight: '28px',
        backgroundColor: 'rgba(110, 123, 247, 0)'
      },

    Mobile: {
        height: '50px',
        width: '284px',
        fontSize: '16px',
        fontFamily: 'Graphik LC TT',
        paddingLeft:' 74px',
        paddingRight:' 74px',
        paddingBottom: '13px',
        paddingTop: '13px',
        borderBottomRightRadius: '8px',
        borderBottomLeftRadius: '8px',
        borderTopRightRadius: '8px',
        borderTopLeftRadius: '8px',
        fontWeight: '500',
        //letterSpacing: '0.5px',
        textAlign: 'center',
        color: 'rgba(255, 255, 255, 1)',
        lineHeight: '28px',
        backgroundColor: 'rgba(110, 123, 247, 0)'
      },
    },
      getStartedButton: {

       Laptop: {
        height: '56px',
        width: '284px',
        fontSize: '18px',
        fontFamily: 'Graphik LC TT',
        paddingLeft:'90px',
        paddingRight:'90px',
        paddingBottom: '14px',
        paddingTop: '14px',
        borderBottomRightRadius: '8px',
        borderBottomLeftRadius: '8px',
        borderTopRightRadius: '8px',
        borderTopLeftRadius: '8px',
        fontWeight: '500',
        //letterSpacing: '0.5px',
        textAlign: 'center',
        color: 'rgba(24, 23, 28, 1)',
        lineHeight: '28px',
        backgroundColor: 'rgba(255, 255, 255, 1)'
      },

    Mobile: {
        height: '50px',
        width: '284px',
        fontSize: '16px',
        fontFamily: 'Graphik LC TT',
        paddingLeft:'96px',
        paddingRight:'96px',
        paddingBottom: '13px',
        paddingTop: '13px',
        borderBottomRightRadius: '8px',
        borderBottomLeftRadius: '8px',
        borderTopRightRadius: '8px',
        borderTopLeftRadius: '8px',
        fontWeight: '500',
        //letterSpacing: '0.5px',
        textAlign: 'center',
        color: 'rgba(24, 23, 28, 1)',
        lineHeight: '28px',
        backgroundColor: 'rgba(255, 255, 255, 1)'
      },
    },
    buttonSpace: {
      Laptop: {
        rowGap: '20px',
      },
      
      Mobile: {
        columnGap: '10px',
      },
  },
  }
};
